### ISSUE TITLE
Problem with the "make && sudo make install"

### ISSUE THREAD

**Issue by Cuervito93** [kit-cel/gr-gfdm#17]
Good evening, "make && sudo make install". I ran the previous commands as root, in the directory /home/carloshernandezgonzalez, which is my user.

  So, i am now in the directory "/home/carloshernandezgonzalez/gr-gfdm/build" ready to build the "add-on" to GNU Radio , but when I run "make && sudo make install" , this happens:
-----------------------------------------------------------------------------------------------------------------------------
Scanning dependencies of target gnuradio-gfdm
[  2%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/gfdm_utils.cc.o
[  5%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/receiver_kernel_cc.cc.o
[  8%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/modulator_cc_impl.cc.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/sync_cc_impl.cc.o
[ 14%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/cyclic_prefixer_cc_impl.cc.o
[ 17%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/preamble_generator.cc.o
[ 20%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/remove_prefix_cc_impl.cc.o
[ 22%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/simple_modulator_cc_impl.cc.o
[ 25%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/modulator_kernel_cc.cc.o
[ 28%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/add_cyclic_prefix_cc.cc.o
[ 31%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/simple_receiver_cc_impl.cc.o
[ 34%] Building CXX object lib/CMakeFiles/gnuradio-gfdm.dir/improved_sync_algorithm_kernel_cc.cc.o
/home/carloshernandezgonzalez/gr-gfdm/lib/improved_sync_algorithm_kernel_cc.cc: In member function ‘int gr::gfdm::improved_sync_algorithm_kernel_cc::find_peak(float*, int)’:
/home/carloshernandezgonzalez/gr-gfdm/lib/improved_sync_algorithm_kernel_cc.cc:267:52: error: ‘volk_32f_index_max_32u’ was not declared in this scope
       volk_32f_index_max_32u(&nm, vals, ninput_size);
                                                    ^
lib/CMakeFiles/gnuradio-gfdm.dir/build.make:326: recipe for target 'lib/CMakeFiles/gnuradio-gfdm.dir/improved_sync_algorithm_kernel_cc.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-gfdm.dir/improved_sync_algorithm_kernel_cc.cc.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'lib/CMakeFiles/gnuradio-gfdm.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-gfdm.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

------------------------------------------------------------------------------------------------------------------------------

  By the way, if it can be of help to understand this, I have the directory "build" of GNU Radio in "/home/carloshernandezgonzalez".

 Best regards,
 Carlos

**Comment by noc0lour** [comment]
It looks like you either don't have the library `volk` in your includes this C++ not finding headers or your volk version is too old. `32f_index_max_32u` was added in volk `1.2.3` which is the required minimum version then.

**Comment by noc0lour** [comment]
I've updated the `CMakeLists.txt` to actually search for `volk` 1.3 which is usually installed with GNU Radio 3.7.10 and above. the minor release 1.2.3 isn't used in GNU Radio afaik.

**Comment by Cuervito93** [comment]
Thank you so much for your feedback! ^^ I'll update and see what happens.

**Comment by noc0lour** [comment]
You're welcome! Let me know if it works.
